---
name: datahub-api
namespace: datahub
scm: git@github.com:uktrade/data-hub-leeloo.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-datahub/datahub-api-dev
    vars:
      - DEBUG: 1
      - DATAHUB_FRONTEND_BASE_URL: https://datahub-dev.cloudapps.digital
      - DJANGO_SETTINGS_MODULE: config.settings.dev
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-datahub/datahub-api-staging
    vars:
      - DEBUG: 1
      - DATAHUB_FRONTEND_BASE_URL: https://datahub-staging.cloudapps.digital
      - DJANGO_SETTINGS_MODULE: config.settings.staging
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: production
    type: gds
    app: dit-services/datahub/datahub-api
    vars:
      - DEBUG: 1
      - DATAHUB_FRONTEND_BASE_URL: https://datahub.cloudapps.digital
      - DJANGO_SETTINGS_MODULE: config.settings.production
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
