---
name: directory-api
namespace: directory
scm: git@github.com:uktrade/directory-api.git
environments:
  - environment: dev
    type: gds
    app: dit-services/dev-directory/directory-api
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/dev-directory/directory-api-staging
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"

