---
name: sandbox
namespace: shared
scm: git@github.com:uktrade/cf-sample-app-nodejs.git
environments:
  - environment: dev
    type: gds
    app: sandbox/cf-nodejs
    vars:
      - FOO: bar
    secrets: true
    run:
      - "ls -al ${WORKSPACE}"
      - "env | sort"
      - "echo hello\ world"
  - environment: s3
    type: s3
    app: ci-pipeline-s3-test
    vars:
      - S3_WEBSITE_SRC: public
    secrets: true
    run:
      - "ls -al ${WORKSPACE}"
      - "env | sort"
      - "echo hello\ world"
